name: OLX Parser

on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 5 минут
  workflow_dispatch:  # Можно запустить вручную

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: pip install requests beautifulsoup4

      - name: Запуск парсера с дебагом
        run: |
          echo "=== Запуск парсера ==="
          python olx_parser.py 2>&1 | tee debug.log  # Записываем в debug.log

      - name: Вывод содержимого логов
        run: cat debug.log  # Показываем содержимое debug.log в логах GitHub

      - name: Настройка Git
        run: git config --global user.name "github-actions" && git config --global user.email "actions@github.com"

      - name: Авторизация через токен
        run: git remote set-url origin https://github.com/${{ github.repository }}.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Коммит логов и данных
        run: |
          git add olx_ads.json debug.log
          git commit -m "Автоматическое обновление объявлений + debug" || echo "Нет изменений"
          git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:main
